version: '3.8'

services:
  mongodb: &mongodb
    image: mongo:5.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - backend

  server:
    depends_on:
      - mongodb
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    networks:
      - frontend

volumes: 
  db:

networks:
  backend:
  frontend: